#pragma once

#define WINDOW_TITLE "Minesweeper"

#define WINDOW_WIDTH 700
#define WINDOW_HEIGHT 500

#define BOARD_WIDTH 25
#define BOARD_HEIGHT 25

#define BOARD_N_MINES 25

#define RC_TYPE_IMAGE L"KET_IMAGE"
#define RC_TYPE_RECT L"KET_RECT"

#define RC_TILESHEET L"TILESHEET"

#define RC_TILE_NORMAL L"TILE_NORMAL"
#define RC_TILE_PRESSED L"TILE_PRESSED"
#define RC_TILE_FLAGGED L"TILE_FLAGGED"
#define RC_TILE_BOMB L"TILE_BOMB"
#define RC_TILE_BOMB_RED L"TILE_BOMB_RED"
#define RC_TILE_BOMB_RED L"TILE_BOMB_RED"

#define RC_TILE_1 L"TILE_1"
#define RC_TILE_2 L"TILE_2"
#define RC_TILE_3 L"TILE_3"
#define RC_TILE_4 L"TILE_4"
#define RC_TILE_5 L"TILE_5"
#define RC_TILE_6 L"TILE_6"
#define RC_TILE_7 L"TILE_7"
#define RC_TILE_8 L"TILE_8"